steps:
  # 1. Instalar dependências
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install', '--legacy-peer-deps']
    id: 'install-deps'

  # 2. Executar migrações do Prisma com Cloud SQL Proxy
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'run'
      - '--rm'
      - '--network'
      - 'cloudbuild'
      - '-v'
      - '/workspace:/workspace'
      - '-w'
      - '/workspace'
      - '--entrypoint'
      - 'bash'
      - 'node:18'
      - 'scripts/migrate.sh'
    id: 'run-migrations'
    waitFor: ['install-deps']
    secretEnv: ['DATABASE_URL']

  # 3. Construir imagem da aplicação
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/mesarpg:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/mesarpg:latest'
      - '.'
    id: 'build-app'
    waitFor: ['run-migrations']

  # 4. Push da imagem para Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/mesarpg:$COMMIT_SHA'
    id: 'push-app'
    waitFor: ['build-app']

  # 5. Deploy no Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'mesarpg'
      - '--image'
      - 'gcr.io/$PROJECT_ID/mesarpg:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'
      - '--add-cloudsql-instances'
      - 'cason-471520:us-central1:mesarpg-db-instance'
      - '--set-secrets'
      - 'DATABASE_URL=DATABASE_URL:latest,NEXTAUTH_SECRET=NEXTAUTH_SECRET:latest'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
    id: 'deploy-cloud-run'
    waitFor: ['push-app']

images:
  - 'gcr.io/$PROJECT_ID/mesarpg:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/mesarpg:latest'

# Disponibiliza os segredos do Secret Manager
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/DATABASE_URL/versions/latest
      env: 'DATABASE_URL'
    - versionName: projects/$PROJECT_ID/secrets/NEXTAUTH_SECRET/versions/latest
      env: 'NEXTAUTH_SECRET'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
