steps:
  # 1. Instala as dependências do projeto
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install', '--legacy-peer-deps']
    id: 'npm-install'

  # 2. Roda as migrações do Prisma via IP Privado
  - name: 'gcr.io/cloud-builders/npm'
    id: 'prisma-migrate'
    waitFor: ['npm-install']
    secretEnv: ['DATABASE_URL']
    entrypoint: 'npm'
    args:
      - 'run'
      - 'db:migrate'

  # 3. Faz o build e o deploy no Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'cloud-run-deploy'
    waitFor: ['prisma-migrate']
    args:
      - 'run'
      - 'deploy'
      - 'mesarpg' # Nome do serviço no Cloud Run
      - '--source'
      - '.'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated' # Permite acesso público ao site
      - '--add-cloudsql-instances=cason-471520:us-central1:mesarpg-db-instance'
      - '--update-secrets=DATABASE_URL=DATABASE_URL:latest,NEXTAUTH_SECRET=NEXTAUTH_SECRET:latest'

# Disponibiliza os segredos do Secret Manager para os passos de build
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/DATABASE_URL_PRIVATE/versions/latest
      env: 'DATABASE_URL'

options:
  logging: CLOUD_LOGGING_ONLY
