steps:
  # 1. Build da imagem custom (para rodar migrations)
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/mesa-builder", "-f", "Dockerfile.builder", "."]

  # 2. Rodar migrações usando a imagem custom + Cloud SQL
  - name: "gcr.io/google-appengine/exec-wrapper"
    args:
      - "-i"
      - "gcr.io/$PROJECT_ID/mesa-builder"
      - "-s"
      - "cason-471520:us-central1:mesarpg-db-instance"
      - "--"
      - "npm"
      - "run"
      - "db:migrate"
    id: prisma-migrate
    secretEnv:
      - DATABASE_URL

  # 3. Build da imagem final para rodar no Cloud Run
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/mesa-app", "."]

  # 4. Push da imagem final para o Container Registry (ou Artifact Registry)
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/mesa-app"]

  # 5. Deploy no Cloud Run
  - name: "gcr.io/google-cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "mesa-app"
      - "--image"
      - "gcr.io/$PROJECT_ID/mesa-app"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--port"
      - "8080"
      - "--set-secrets"
      - "DATABASE_URL=DATABASE_URL:latest,NEXTAUTH_SECRET=NEXTAUTH_SECRET:latest"

images:
  - "gcr.io/$PROJECT_ID/mesa-app"